version: "3.8"

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_URL=http://fastapi:8000   # <-- add this line
    depends_on:
      - fastapi
    restart: always